# Generated by Django 5.0.6 on 2024-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(to="client.client"),
        ),
    ]
