# Generated by Django 5.0.6 on 2024-07-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("deactivate_mailing", "Can deactivate mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
