# Generated by Django 5.0.6 on 2024-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите Ф.И.О клиента",
                        max_length=255,
                        verbose_name="Ф.И.О клиента",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите E-mail клиента",
                        max_length=254,
                        unique=True,
                        verbose_name="E-mail клиента",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий клиента",
                        null=True,
                        verbose_name="Комментарий клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
